baseURL = "code"
# baseURL = "https://chana-chh.github.io/code/"
languageCode = "sr"
title = "ChaSha Coding Blog"
paginate = 5
paginatePath = "strana"
pluralizeListTitles = false
pygmentsCodeFences = true
footnoteReturnLinkContents = "[nazad]"
pygmentsStyle = "native" # monokai
publishDir = "docs"
[taxonomies]
	kategorija = "kategorije"
	rec = "reči"
	autor = "autori"
	mesec = "arhiva"
